// 可爱卡通风（crypto-cat 主题）
export const cartoon = {
  id: 'cartoon',
  name: '可爱卡通',
  icon: '🐱',
  antd: {
    token: {
      colorPrimary: '#f472b6',
      colorSuccess: '#34d399',
      colorWarning: '#fbbf24',
      colorError: '#f87171',
      colorInfo: '#a78bfa',
      colorTextBase: '#4a1a4a',
      colorBgBase: '#fff5fa',
      colorBgContainer: '#ffffff',
      colorBgElevated: '#ffffff',
      colorBorder: '#fbcfe8',
      colorBorderSecondary: '#fce7f3',
      borderRadius: 20,
      fontFamily: "'Fredoka', 'Comic Neue', sans-serif",
      fontSize: 14,
    },
    components: {
      Layout: {
        bodyBg: '#fff5fa',
        headerBg: '#ffffff',
        headerColor: '#4a1a4a',
        headerHeight: 64,
        headerPadding: '0 24px',
      },
      Menu: {
        itemColor: '#7c3aed',
        itemHoverColor: '#f472b6',
        itemSelectedBg: '#fce7f3',
        itemSelectedColor: '#f472b6',
        horizontalItemSelectedColor: '#f472b6',
        horizontalItemHoverColor: '#f472b6',
      },
      Button: {
        primaryShadow: '0 4px 0 #ec4899',
        borderRadius: 16,
        fontWeight: 600,
      },
      Card: {
        colorBgContainer: '#ffffff',
        boxShadowTertiary: '0 4px 0 #fbcfe8, 0 8px 16px rgba(244, 114, 182, 0.15)',
      },
      Modal: {
        contentBg: '#ffffff',
        titleColor: '#4a1a4a',
        borderRadiusLG: 24,
      },
    },
  },
  cssVars: {
    '--bg-primary': '#fff5fa',
    '--bg-secondary': '#ffffff',
    '--bg-gradient': 'linear-gradient(135deg, #fce7f3 0%, #fff5fa 50%, #f3e8ff 100%)',
    '--text-primary': '#4a1a4a',
    '--text-secondary': '#9333ea',
    '--accent-pink': '#f472b6',
    '--accent-purple': '#a78bfa',
    '--accent-blue': '#60a5fa',
    '--accent-cyan': '#22d3ee',
    '--border-color': '#fbcfe8',
    '--shadow-glow-pink': '0 4px 0 #ec4899, 0 8px 16px rgba(244, 114, 182, 0.3)',
    '--shadow-glow-purple': '0 4px 0 #a78bfa, 0 8px 16px rgba(167, 139, 250, 0.3)',
    '--shadow-card': '0 4px 0 #fbcfe8, 0 8px 16px rgba(244, 114, 182, 0.15)',
    '--font-family': "'Fredoka', 'Comic Neue', sans-serif",
  },
  bgImage: 'linear-gradient(135deg, #fce7f3 0%, #fff5fa 50%, #f3e8ff 100%)',
  bannerImage: 'linear-gradient(180deg, rgba(244, 114, 182, 0.15) 0%, transparent 60%)',
};
